services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: quad-mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongPassword!123
      - MSSQL_PID=Developer   # CDC-ready (Express nu suportă CDC)
    ports: ["1433:1433"]
    volumes:
      - ./db/mssql/init:/docker-entrypoint-initdb.d

  dotnet-api:
    build:
      context: ./services/dotnet-api
      dockerfile: Dockerfile
    container_name: quad-dotnet-api
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - DB_CONN=Server=mssql;Database=appdb;User Id=sa;Password=StrongPassword!123;TrustServerCertificate=True;
    ports: ["5001:8080"]
    depends_on:
      - mssql
