IF DB_ID('appdb') IS NULL BEGIN CREATE DATABASE appdb; END
GO
USE appdb;
GO

IF OBJECT_ID('dbo.Products') IS NULL
BEGIN
  CREATE TABLE dbo.Products (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Sku NVARCHAR(50) NOT NULL UNIQUE,
    Name NVARCHAR(200) NOT NULL,
    Price DECIMAL(12,2) NOT NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
  );
END
GO

-- trigger de updated_at
IF OBJECT_ID('dbo.trg_Products_Updated') IS NOT NULL DROP TRIGGER dbo.trg_Products_Updated;
GO
CREATE TRIGGER dbo.trg_Products_Updated ON dbo.Products
AFTER UPDATE AS
BEGIN
  SET NOCOUNT ON;
  UPDATE p SET UpdatedAt=SYSUTCDATETIME()
  FROM dbo.Products p
  JOIN inserted i ON p.Id=i.Id;
END
GO
